##
## EPITECH PROJECT, 2024
## Raytracer
## File description:
## Makefile
##

all:
	cd sphere && make
	cd cone && make
	cd cylinder && make
	cd plane && make

clean:
	cd sphere && make clean
	cd cone && make clean
	cd cylinder && make clean
	cd plane && make clean

fclean: clean
	cd sphere && make fclean
	cd cone && make fclean
	cd cylinder && make fclean
	cd plane && make fclean

re:	fclean all

.PHONY: clean fclean re